version: "3.9"
services:
  web:
    image: bundle/web:1.0
    ports:
      - 8080:8080
  api:
    image: bundle/api:1.0
    ports:
      - 8020:8020
  repo:
    image: bundle/repo:1.0
    ports:
      - 8060:8060
  db:
    image: bundle/db:1.0
    ports:
      - 8040:8040
