version: "3.7"
services:
  web:
    image: golang
    command: sh -c "go install && web"
    ports:
      - 8080:8080
    working_dir: /bundle/web
    environment:
    DATABASE_PORT: 8040
    REPO_PORT: 8060
    WEB_PORT: 8080
    API_PORT: 8020
    AUTH_PORT: 8030
  api:
    image: golang
    command: sh -c "go install && api"
    ports:
      - 8020:8020
    working_dir: /bundle/api
    environment:
      DATABASE_PORT: 8040
      REPO_PORT: 8060
      WEB_PORT: 8080
      API_PORT: 8020
      AUTH_PORT: 8030
  repo:
    image: golang
    command: sh -c "go install && repo"
    ports:
      - 8060:8060
    working_dir: /bundle/repo
    environment:
      DATABASE_PORT: 8040
      REPO_PORT: 8060
      WEB_PORT: 8080
      API_PORT: 8020
      AUTH_PORT: 8030
  db:
    image: golang
    command: sh -c "go install && db"
    ports:
      - 8040:8040
    working_dir: /bundle/db
    environment:
      DATABASE_PORT: 8040
      REPO_PORT: 8060
      WEB_PORT: 8080
      API_PORT: 8020
      AUTH_PORT: 8030
