version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./images/web/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ".env"
  gate:
    build:
      context: .
      dockerfile: ./images/gate/Dockerfile
    ports:
      - 8020:8020
    env_file:
      - ".env"
  repo:
    build:
      context: .
      dockerfile: ./images/repo/Dockerfile
    ports:
      - 8060:8060
    env_file:
      - ".env"
  db:
    build:
      context: .
      dockerfile: ./images/db/Dockerfile
    ports:
      - 8040:8040
    env_file:
      - ".env"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    env_file:
      - ".env"
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    volumes:
      - /vault/file
    env_file:
      - ".env"
