version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./images/web/Dockerfile
    ports:
      - 8080:8080
  api:
    build:
      context: .
      dockerfile: ./images/api/Dockerfile
    ports:
      - 8020:8020
  repo:
    build:
      context: .
      dockerfile: ./images/repo/Dockerfile
      args:
        awsid: ${AWS_ACCESS_KEY_ID}
        awssecret: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8060:8060
  db:
    build:
      context: .
      dockerfile: ./images/db/Dockerfile
    ports:
      - 8040:8040
